JuliaArrays/FixedSizeArrays.jl

src/FixedSizeArrays.jl
This gets rid of a lot of the compiler internals that aren't needed. It also changes the representation of `FixedSizeArray` to a `Memory` rather than a `MemoryRef` because the `MemoryRef` was only needed to allow the backing to change.
=> cleanup and slightly improve speed

test/runtests.jl
The previous tests were flattening the matrix before setting/accessing the elements, thus not really exercising the 2D indexing of the new data type.
=> Improve test for `FixedSizeMatrix`

src/FixedSizeArrays.jl, test/runtests.jl
Now `similar` will be able to return `FixedSizeArray`s instead of `Array`s.
Updates #4
=> specialize `similar`

src/FixedSizeArrays.jl, test/runtests.jl
Goals:
* support `undef` constructor methods with incompletely specified type, lacking dimensionality, e.g., `FixedArray{Int}(undef, 3, 7)`
* support `undef` constructor methods with `size` passed as tuple instead of as `Vararg`
To make this possible, it was necessary to get rid of the automatically generated inner constructor methods, to prevent ambiguity.
A specific reason why these changes are necessary is that some methods of `similar` defined in `Base` expect such constructors to exist.
=> revamp constructors

src/FixedSizeArrays.jl, test/runtests.jl
=> conversion from `AbstractArray` and converting constructors

src/FixedSizeArrays.jl, test/runtests.jl
Fixes #14
The below benchmark shows many orders of magnitude of performance improvement, more so for arrays with many `undef` elements:
```julia
using BenchmarkTools, FixedSizeArrays
function new_arr(len, prob)
ret = FixedSizeVector{FixedSizeVector{Nothing}}(undef, len)
for i ∈ eachindex(ret)
if rand() < prob
ret[i] = eltype(ret)(undef, 0)
end
end
ret
end
function assigned_count(arr)
cnt = 0
for i ∈ eachindex(arr)
cnt += isassigned(arr, i)
end
cnt
end
len = 10000
arr = new_arr(len, 0.1);
@btime assigned_count(arr)
arr = new_arr(len, 0.5);
@btime assigned_count(arr)
arr = new_arr(len, 0.9);
@btime assigned_count(arr)
versioninfo()
```
=> specialize `isassigned` for performance

src/FixedSizeArrays.jl, test/runtests.jl
The fallback generic implementation of `copyto!` uses `setindex!` in an elementwise manner. Instead base the implementation on `unsafe_copyto!`. This improves the performance of `copyto!`, thus it also improves the performance of `copy!`, `copy` and of broadcasted operations.
This change only applies when copying between two `FixedSizeArray`s, or between a `Memory` and a `FixedSizeArray`.
Fixes #19
=> specialize `copyto!` for performance

test/runtests.jl
=> test for negative-length `copyto!` call

src/FixedSizeArrays.jl, test/runtests.jl
Makes `pointer(::FixedSizeArray, ::Int)` work.
Fixes #25
=> implement `Base.elsize` for the strided arrays interface

src/FixedSizeArrays.jl
`AbstractArray` constructors that take `AbstractArray` usually copy the input array, something that our inner constructor doesn't do. So it seems safer to remove the inner constructor from our public API.
=> make the inner constructor an internal implementation detail

src/FixedSizeArrays.jl, test/runtests.jl
This is analogous with the behavior for `Array` and should make type stability easier for some uses.
=> specialize `reshape`, ensuring it returns `FixedSizeArray`

src/FixedSizeArrays.jl, test/runtests.jl
`Array` supports the same for their `undef` constructor (although `Memory` doesn't), so `FixedSizeArray` probably should, too.
=> support specifying dimensions with non-`Int` integers

README.md, src/FixedSizeArrays.jl, test/runtests.jl
Makes constructing `FixedSizeArray`s more convenient!
Inspired by
https://github.com/JuliaLang/julia/issues/36288
This currently ignores `Base.IteratorElType`, xref https://discourse.julialang.org/t/i-dont-get-base-iteratoreltype/113604
The allocations in some code paths are probably excessive/could be optimized. But I guess this is good for a start.
Fixes #20
=> introduce function `collect_as` for construction from an iterator

src/FixedSizeArrays.jl
https://github.com/JuliaLang/julia/issues/51962#issuecomment-1787811957
> It is generally best to implement cconvert (since it is not unsafe),
> and generally required to call both functions as well (mimicking the
> behavior defined for ccall)
=> specialize `cconvert` instead of `unsafe_convert`

.github/workflows/UnitTests.yml, src/FixedSizeArrays.jl, test/runtests.jl
This approach isolates us from possible changes in the `GenericMemory` design while leaving open the possibility of supporting other underlying storage types in the future.
Fixes #33
=> support `GenericMemory` by making the storage type a parameter

src/FixedSizeArrays.jl
=> Define `Base.dataids` method for FixedSizeArrays

src/FixedSizeArrays.jl, test/runtests.jl
=> Automatically skip boundschecks in `setindex!` when safe to do so

src/FixedSizeArrays.jl, test/runtests.jl
=> define `propertynames(::FixedSizeArray)`

src/FixedSizeArrays.jl, src/collect_as.jl
I think this may be tidier. The `FixedSizeBitArray` method would presumably go right next to this one.
=> move the `dataids` method to the main file

src/FixedSizeArray.jl, test/runtests.jl
Apart from fixing the type piracy, this change moves us from `AbstractArrayStyle{Any}` to `AbstractArrayStyle{N}`. This seems like a good idea because that's what `Array` uses.
Fixes #77
=> introduce a custom `Broadcast.AbstractArrayStyle` subtype

src/FixedSizeArray.jl, src/FixedSizeArrays.jl
They're not `FixedSizeArray`-specific, might be useful for `FixedSizeBitArray`.
=> move `GenericMemory`-related definitions to the main file

src/FixedSizeArray.jl, src/collect_as.jl, test/runtests.jl
The behavior is supposed to stay the same, except for the case when the input iterator is empty.
Ideas:
* First collect into a `FixedSizeVector`.
* Use `iterate`, without calling `length`, `size` or `axes` on the iterator.
* Avoid using existing `collect` or `map` methods from `Base`, to prevent the output element type from depending on type inference.
* For an empty input iterator, if the desired element type for the output is not specified, consult `eltype(iterator)`. When `!isconcretetype(eltype(iterator))`, just use `Union{}` for the output element type.
* A drawback of this approach is type instability of `collect_as` when the output element type is not given and the iterator has neither constant-length nor exactly known element type. This is, however, required to prevent the output …
=> rewrite `collect_as`

src/FixedSizeArray.jl, src/collect_as.jl, test/runtests.jl
Prevent doubling in the number of these constructor methods with each additional `FixedSizeArray` type parameter.
I think the code is nicer, too.
=> simplify `undef`-taking constructors

src/FixedSizeArray.jl, src/collect_as.jl, test/runtests.jl
Before this PR `collect_as` had to use a type assert on the return value to make sure the return value is of the type requested by the user. This is necessary because of UnionAll types with non-default constraints on their type parameters, such as `FixedSizeVector{T} where {T <: Number}`, because accessing the specific constraint is not currently possible in Julia in a supported way.
This change removes the type assert, instead throwing early, as soon as it is recognized that the requested return type is not among the allowed types, which are known-good, in the sense that the return value we produce ends up being of the requested type as expected.
Benefits:
* a type assert of nonconcrete type is not required any more (those can be expensive)
* the throw happens earlier than before
Future …
=> fail early for `FixedSizeArray` subtypes we can't handle

src/FixedSizeArray.jl
The type assert:
* Is not always concrete, which might cause performance issues.
* Doesn't seem to be necessary, either for good type inference or for correctness.
* If it were necessary, it'd make more sense to insert it earlier, into the body of one of the constructors (which `convert` forwards to).
=> delete an unnecessary type assert from a `convert` method

src/FixedSizeArray.jl
This is more self-documenting. It also leads to more understandable output of `methods` and `MethodError`s.
=> consistently name the type parameters of `FixedSizeArray`

Project.toml, src/FixedSizeArrays.jl, src/stdlibs.jl, test/Project.toml, test/runtests.jl
The `rand!` method for `Memory` is vectorized and faster than the generic method for `AbstractArray` (which is the one currently being hit by `FixedSizeArray`s) at least for sufficiently long vectors.
I spotted this while looking into performance differences in https://github.com/JuliaArrays/FixedSizeArrays.jl/discussions/62#discussioncomment-12319065.
=> Add faster method for `rand!`

docs/src/reference.md, src/BoundsErrorLight.jl, src/FixedSizeArray.jl, src/FixedSizeArrays.jl, test/runtests.jl
Unlike `BoundsError`, `BoundsErrorLight` doesn't store the array, potentially helping escape analysis.
=> introduce `BoundsErrorLight`, use instead of `BoundsError`

src/FixedSizeArray.jl, test/runtests.jl
Merely forwarding to `copy` results in better effect inference, we get `nothrow` and `terminates`.
Fixes #117
=> add method for `getindex(::FixedSizeArray, ::Colon)`

src/FixedSizeArray.jl
As far as I understand, a `typeassert` is zero-cost when the RHS is known upfront and concrete. Otherwise it can be costly, assuming it's not just optimized out.
=> avoid possibly costly `typeassert`

Project.toml, docs/Project.toml, docs/src/usage.md, ext/AdaptExt.jl, test/Project.toml, test/runtests.jl
Hello, I was playing around with this package and in my use cases we have a lot of wrapper types around arrays, where we want to preserve the wrapper. We commonly do that with `Adapt.jl`, so far mostly to move things to the GPU. But we could also use it to move things from `Array` to `FixedSizeArray` with this PR:
```julia
julia> using FixedSizeArrays, Adapt
julia> arr = transpose([10 20; 30 14])
2×2 transpose(::Matrix{Int64}) with eltype Int64:
10  30
20  14
julia> FixedSizeArray(arr)
2×2 FixedSizeArray{Int64, 2, Memory{Int64}}:
10  30
20  14
julia> adapt(FixedSizeArray, arr) # without the extensions this would still be typeof(arr)
2×2 transpose(::FixedSizeArray{Int64, 2, Memory{Int64}}) with eltype Int64:
10  30
20  14
```
I can also turn the example into a test if this PR is …
=> Add Adapt.jl package extension to construct FixedSizeArrays which preserve wrapper types
